-- tests for rich message and 10.x input-media builders
local api = require('spec.test_helper')

describe('rich builders', function()

    describe('input types', function()
        it('input_rich_message keeps html, is_rtl and skip_entity_detection', function()
            local m = api.input_rich_message({ html = '<b>x</b>', is_rtl = true, skip_entity_detection = true })
            assert.equals('<b>x</b>', m.html)
            assert.is_nil(m.markdown)
            assert.is_true(m.is_rtl)
            assert.is_true(m.skip_entity_detection)
        end)

        it('input_rich_message supports markdown', function()
            local m = api.input_rich_message({ markdown = '*x*' })
            assert.equals('*x*', m.markdown)
            assert.is_nil(m.html)
        end)

        it('input_rich_message tolerates no args', function()
            assert.is_table(api.input_rich_message())
        end)

        it('input_rich_message_content wraps a rich message', function()
            local c = api.input_rich_message_content({ html = 'x' })
            assert.equals('x', c.rich_message.html)
        end)

        it('link builds a url object', function()
            assert.equals('https://x', api.link('https://x').url)
        end)

        it('rich_message holds blocks and is_rtl', function()
            local blocks = { api.rich_block_paragraph('p') }
            local m = api.rich_message(blocks, true)
            assert.equals(blocks, m.blocks)
            assert.is_true(m.is_rtl)
        end)
    end)

    describe('rich text', function()
        it('uniform { type, text } variants set the right discriminator', function()
            local cases = {
                bold = api.rich_text_bold, italic = api.rich_text_italic,
                underline = api.rich_text_underline, strikethrough = api.rich_text_strikethrough,
                spoiler = api.rich_text_spoiler, subscript = api.rich_text_subscript,
                superscript = api.rich_text_superscript, marked = api.rich_text_marked,
                code = api.rich_text_code
            }
            for expected_type, fn in pairs(cases) do
                local t = fn('hello')
                assert.equals(expected_type, t.type)
                assert.equals('hello', t.text)
            end
        end)

        it('accepts nested rich text as the text field', function()
            local nested = api.rich_text_bold(api.rich_text_italic('x'))
            assert.equals('bold', nested.type)
            assert.equals('italic', nested.text.type)
        end)

        it('custom_emoji has no text field', function()
            local t = api.rich_text_custom_emoji('emoji_id', 'fire')
            assert.equals('custom_emoji', t.type)
            assert.equals('emoji_id', t.custom_emoji_id)
            assert.equals('fire', t.alternative_text)
            assert.is_nil(t.text)
        end)

        it('mathematical_expression has no text field', function()
            local t = api.rich_text_mathematical_expression('x^2')
            assert.equals('mathematical_expression', t.type)
            assert.equals('x^2', t.expression)
            assert.is_nil(t.text)
        end)

        it('anchor has no text field', function()
            local t = api.rich_text_anchor('top')
            assert.equals('anchor', t.type)
            assert.equals('top', t.name)
            assert.is_nil(t.text)
        end)

        it('date_time carries unix_time and format', function()
            local t = api.rich_text_date_time('when', 1700000000, 'yyyy')
            assert.equals('date_time', t.type)
            assert.equals(1700000000, t.unix_time)
            assert.equals('yyyy', t.date_time_format)
        end)

        it('url, email, phone and bank card carry their value fields', function()
            assert.equals('https://x', api.rich_text_url('t', 'https://x').url)
            assert.equals('a@b.c', api.rich_text_email_address('t', 'a@b.c').email_address)
            assert.equals('+44', api.rich_text_phone_number('t', '+44').phone_number)
            assert.equals('1234', api.rich_text_bank_card_number('t', '1234').bank_card_number)
        end)

        it('mention, hashtag, cashtag and bot_command carry their value fields', function()
            assert.equals('user', api.rich_text_mention('t', 'user').username)
            assert.equals('tag', api.rich_text_hashtag('t', 'tag').hashtag)
            assert.equals('USD', api.rich_text_cashtag('t', 'USD').cashtag)
            assert.equals('/start', api.rich_text_bot_command('t', '/start').bot_command)
        end)

        it('text_mention carries the user object', function()
            local t = api.rich_text_text_mention('t', { id = 7 })
            assert.equals('text_mention', t.type)
            assert.equals(7, t.user.id)
        end)

        it('anchor_link, reference and reference_link carry their targets', function()
            assert.equals('a', api.rich_text_anchor_link('t', 'a').anchor_name)
            assert.equals('r', api.rich_text_reference('t', 'r').name)
            assert.equals('r', api.rich_text_reference_link('t', 'r').reference_name)
        end)
    end)

    describe('rich blocks', function()
        it('paragraph, footer and thinking carry text', function()
            assert.equals('paragraph', api.rich_block_paragraph('p').type)
            assert.equals('footer', api.rich_block_footer('f').type)
            local th = api.rich_block_thinking('...')
            assert.equals('thinking', th.type)
            assert.equals('...', th.text)
        end)

        it('heading carries a size', function()
            local h = api.rich_block_heading('h', 2)
            assert.equals('heading', h.type)
            assert.equals(2, h.size)
        end)

        it('preformatted uses the "pre" discriminator', function()
            local p = api.rich_block_preformatted('code', 'lua')
            assert.equals('pre', p.type)
            assert.equals('lua', p.language)
        end)

        it('divider carries only its type', function()
            local d = api.rich_block_divider()
            assert.equals('divider', d.type)
            assert.is_nil(d.text)
        end)

        it('blockquote and pullquote use their own discriminators', function()
            assert.equals('blockquote', api.rich_block_blockquote({}, 'c').type)
            assert.equals('pullquote', api.rich_block_pullquote('t', 'c').type)
        end)

        it('list and list_item compose', function()
            local item = api.rich_block_list_item('one', { api.rich_block_paragraph('p') }, { type = '1', value = 1 })
            assert.equals('one', item.label)
            assert.equals('1', item.type)
            assert.equals(1, item.value)
            local list = api.rich_block_list({ item })
            assert.equals('list', list.type)
            assert.equals(item, list.items[1])
        end)

        it('table and table_cell compose with options', function()
            local cell = api.rich_block_table_cell('c', { is_header = true, colspan = 2, align = 'center' })
            assert.is_true(cell.is_header)
            assert.equals(2, cell.colspan)
            assert.equals('center', cell.align)
            local tbl = api.rich_block_table({ { cell } }, { is_bordered = true })
            assert.equals('table', tbl.type)
            assert.is_true(tbl.is_bordered)
            assert.equals(cell, tbl.cells[1][1])
        end)

        it('details carries summary, blocks and is_open', function()
            local d = api.rich_block_details('sum', {}, true)
            assert.equals('details', d.type)
            assert.equals('sum', d.summary)
            assert.is_true(d.is_open)
        end)

        it('map carries location and zoom', function()
            local m = api.rich_block_map({ latitude = 1, longitude = 2 }, { zoom = 15, width = 100 })
            assert.equals('map', m.type)
            assert.equals(15, m.zoom)
            assert.equals(1, m.location.latitude)
        end)

        it('media blocks carry their payload and spoiler flag', function()
            assert.equals('animation', api.rich_block_animation({ file_id = 'a' }, { has_spoiler = true }).type)
            assert.equals('audio', api.rich_block_audio({ file_id = 'a' }).type)
            local photo = api.rich_block_photo({ { file_id = 'p' } }, { has_spoiler = true })
            assert.equals('photo', photo.type)
            assert.is_true(photo.has_spoiler)
            assert.equals('video', api.rich_block_video({ file_id = 'v' }).type)
            assert.equals('voice_note', api.rich_block_voice_note({ file_id = 'vn' }).type)
        end)

        it('caption helper holds text and credit', function()
            local c = api.rich_block_caption('cap', 'src')
            assert.equals('cap', c.text)
            assert.equals('src', c.credit)
        end)

        it('collage and slideshow hold blocks and an optional caption', function()
            local cap = api.rich_block_caption('c')
            assert.equals('collage', api.rich_block_collage({}, cap).type)
            assert.equals('slideshow', api.rich_block_slideshow({}, cap).type)
        end)

        it('anchor and mathematical_expression blocks carry their fields', function()
            assert.equals('top', api.rich_block_anchor('top').name)
            assert.equals('x^2', api.rich_block_mathematical_expression('x^2').expression)
        end)
    end)
end)

describe('10.x input-media builders', function()
    it('input_media_sticker returns object and files', function()
        local obj, files = api.input_media_sticker('sticker_id', 'fire')
        assert.equals('sticker', obj.type)
        assert.equals('fire', obj.emoji)
        assert.equals('sticker_id', files.media)
    end)

    it('input_media_location coerces coordinates to numbers', function()
        local obj = api.input_media_location('1.5', '2.5', '100')
        assert.equals('location', obj.type)
        assert.equals(1.5, obj.latitude)
        assert.equals(2.5, obj.longitude)
        assert.equals(100, obj.horizontal_accuracy)
    end)

    it('input_media_venue carries address and optional fields', function()
        local obj = api.input_media_venue(1, 2, 'Title', 'Addr', { foursquare_id = 'fsq' })
        assert.equals('venue', obj.type)
        assert.equals('Title', obj.title)
        assert.equals('Addr', obj.address)
        assert.equals('fsq', obj.foursquare_id)
    end)

    it('input_media_live_photo returns object and both files', function()
        local obj, files = api.input_media_live_photo('vid', 'pic', { has_spoiler = true })
        assert.equals('live_photo', obj.type)
        assert.is_true(obj.has_spoiler)
        assert.equals('vid', files.media)
        assert.equals('pic', files.photo)
    end)

    it('input_media_link carries a url', function()
        local obj = api.input_media_link('https://x')
        assert.equals('link', obj.type)
        assert.equals('https://x', obj.url)
    end)

    it('input_paid_media_live_photo returns object and both files', function()
        local obj, files = api.input_paid_media_live_photo('vid', 'pic')
        assert.equals('live_photo', obj.type)
        assert.equals('vid', files.media)
        assert.equals('pic', files.photo)
    end)
end)
