-- tests for bot api 10.0 / 10.1 methods and parameter extensions
local api = require('spec.test_helper')
local json = require('dkjson')

describe('Bot API 10.x methods', function()
    before_each(function()
        api._clear_requests()
    end)

    describe('rich messages (10.1)', function()
        it('send_rich_message hits the correct endpoint with chat_id', function()
            api.send_rich_message(123, { html = '<b>hi</b>' })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendRichMessage'))
            assert.equals(123, req.parameters.chat_id)
        end)

        it('send_rich_message JSON-encodes the rich_message object', function()
            api.send_rich_message(123, { html = '<b>hi</b>', is_rtl = true })
            local decoded = json.decode(api._last_request().parameters.rich_message)
            assert.equals('<b>hi</b>', decoded.html)
            assert.is_true(decoded.is_rtl)
        end)

        it('send_rich_message passes a pre-encoded string rich_message through', function()
            api.send_rich_message(123, '{"html":"x"}')
            assert.equals('{"html":"x"}', api._last_request().parameters.rich_message)
        end)

        it('send_rich_message passes and JSON-encodes opts', function()
            api.send_rich_message(123, { markdown = '*hi*' }, {
                business_connection_id = 'biz',
                message_thread_id = 7,
                direct_messages_topic_id = 9,
                disable_notification = true,
                protect_content = true,
                allow_paid_broadcast = true,
                message_effect_id = 'fx',
                suggested_post_parameters = { price = { amount = 5 } },
                reply_parameters = api.reply_parameters(42, 123, true),
                reply_markup = api.inline_keyboard():row(api.row():callback_data_button('A', 'a'))
            })
            local req = api._last_request()
            assert.equals('biz', req.parameters.business_connection_id)
            assert.equals(7, req.parameters.message_thread_id)
            assert.equals(9, req.parameters.direct_messages_topic_id)
            assert.is_true(req.parameters.disable_notification)
            assert.equals('fx', req.parameters.message_effect_id)
            assert.equals(5, json.decode(req.parameters.suggested_post_parameters).price.amount)
            assert.equals(42, json.decode(req.parameters.reply_parameters).message_id)
            assert.is_table(json.decode(req.parameters.reply_markup).inline_keyboard)
        end)

        it('send_rich_message_draft passes chat_id, draft_id and rich_message', function()
            api.send_rich_message_draft(55, 99, { html = 'partial' }, { message_thread_id = 3 })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendRichMessageDraft'))
            assert.equals(55, req.parameters.chat_id)
            assert.equals(99, req.parameters.draft_id)
            assert.equals(3, req.parameters.message_thread_id)
            assert.equals('partial', json.decode(req.parameters.rich_message).html)
        end)

        it('edit_message_text JSON-encodes a rich_message opt', function()
            api.edit_message_text(123, 456, nil, { rich_message = { html = '<i>x</i>' } })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/editMessageText'))
            assert.equals('<i>x</i>', json.decode(req.parameters.rich_message).html)
        end)
    end)

    describe('live photos (10.0)', function()
        it('send_live_photo sends both files and hits the endpoint', function()
            api.send_live_photo(123, 'live_id', 'photo_id', { caption = 'cap', has_spoiler = true })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendLivePhoto'))
            assert.equals(123, req.parameters.chat_id)
            assert.equals('cap', req.parameters.caption)
            assert.is_true(req.parameters.has_spoiler)
            assert.equals('live_id', req.file.live_photo)
            assert.equals('photo_id', req.file.photo)
        end)

        it('send_live_photo JSON-encodes caption_entities and reply_markup', function()
            api.send_live_photo(1, 'l', 'p', {
                caption_entities = {{ type = 'bold', offset = 0, length = 1 }},
                reply_markup = api.inline_keyboard():row(api.row():callback_data_button('A', 'a'))
            })
            local req = api._last_request()
            assert.equals('bold', json.decode(req.parameters.caption_entities)[1].type)
            assert.is_table(json.decode(req.parameters.reply_markup).inline_keyboard)
        end)
    end)

    describe('reaction deletion (10.0)', function()
        it('delete_message_reaction passes chat_id, message_id and actor opts', function()
            api.delete_message_reaction(123, 456, { user_id = 7, actor_chat_id = 8 })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/deleteMessageReaction'))
            assert.equals(123, req.parameters.chat_id)
            assert.equals(456, req.parameters.message_id)
            assert.equals(7, req.parameters.user_id)
            assert.equals(8, req.parameters.actor_chat_id)
        end)

        it('delete_message_reaction works without opts', function()
            api.delete_message_reaction(123, 456)
            local req = api._last_request()
            assert.equals(456, req.parameters.message_id)
        end)

        it('delete_all_message_reactions takes chat_id but no message_id', function()
            api.delete_all_message_reactions(123, { user_id = 7 })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/deleteAllMessageReactions'))
            assert.equals(123, req.parameters.chat_id)
            assert.equals(7, req.parameters.user_id)
            assert.is_nil(req.parameters.message_id)
        end)
    end)

    describe('guest mode (10.0)', function()
        it('answer_guest_query JSON-encodes a table result', function()
            api.answer_guest_query('q1', { type = 'article', id = '1', title = 'T' })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/answerGuestQuery'))
            assert.equals('q1', req.parameters.guest_query_id)
            assert.equals('article', json.decode(req.parameters.result).type)
        end)

        it('answer_guest_query passes a string result through', function()
            api.answer_guest_query('q1', '{"type":"article"}')
            assert.equals('{"type":"article"}', api._last_request().parameters.result)
        end)
    end)

    describe('join request queries (10.1)', function()
        it('answer_chat_join_request_query passes id and result', function()
            api.answer_chat_join_request_query('jq1', 'approve')
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/answerChatJoinRequestQuery'))
            assert.equals('jq1', req.parameters.chat_join_request_query_id)
            assert.equals('approve', req.parameters.result)
        end)

        it('send_chat_join_request_web_app passes id and web_app_url', function()
            api.send_chat_join_request_web_app('jq1', 'https://example.com/app')
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendChatJoinRequestWebApp'))
            assert.equals('jq1', req.parameters.chat_join_request_query_id)
            assert.equals('https://example.com/app', req.parameters.web_app_url)
        end)
    end)

    describe('managed bot access settings (10.0)', function()
        it('get_managed_bot_access_settings passes user_id', function()
            api.get_managed_bot_access_settings(42)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/getManagedBotAccessSettings'))
            assert.equals(42, req.parameters.user_id)
        end)

        it('set_managed_bot_access_settings JSON-encodes added_user_ids', function()
            api.set_managed_bot_access_settings(42, true, { added_user_ids = { 1, 2, 3 } })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/setManagedBotAccessSettings'))
            assert.equals(42, req.parameters.user_id)
            assert.is_true(req.parameters.is_access_restricted)
            assert.equals(3, #json.decode(req.parameters.added_user_ids))
        end)

        it('get_user_personal_chat_messages passes user_id and limit', function()
            api.get_user_personal_chat_messages(42, 20)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/getUserPersonalChatMessages'))
            assert.equals(42, req.parameters.user_id)
            assert.equals(20, req.parameters.limit)
        end)
    end)

    describe('parameter extensions', function()
        it('get_chat_administrators passes return_bots', function()
            api.get_chat_administrators(123, { return_bots = true })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/getChatAdministrators'))
            assert.equals(123, req.parameters.chat_id)
            assert.is_true(req.parameters.return_bots)
        end)

        it('get_chat_administrators remains backward compatible without opts', function()
            api.get_chat_administrators(123)
            assert.equals(123, api._last_request().parameters.chat_id)
        end)

        it('send_poll JSON-encodes media, explanation_media and country_codes', function()
            api.send_poll(123, 'Q?', { 'a', 'b' }, {
                media = api.input_media_link('https://x'),
                explanation_media = api.input_media_link('https://y'),
                members_only = true,
                country_codes = { 'GB', 'US' }
            })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendPoll'))
            assert.equals('link', json.decode(req.parameters.media).type)
            assert.equals('https://y', json.decode(req.parameters.explanation_media).url)
            assert.is_true(req.parameters.members_only)
            assert.equals('GB', json.decode(req.parameters.country_codes)[1])
        end)
    end)
end)
