-- tests for the bot api methods added in v3.7 (business accounts, gifts,
-- stories, checklists, verification, prepared inline messages, etc.)
local api = require('spec.test_helper')
local json = require('dkjson')

describe('Missing Bot API methods', function()
    before_each(function()
        api._clear_requests()
    end)

    describe('business account methods', function()
        it('get_business_connection passes business_connection_id', function()
            api.get_business_connection('biz1')
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/getBusinessConnection'))
            assert.equals('biz1', req.parameters.business_connection_id)
        end)

        it('read_business_message passes id, chat_id and message_id', function()
            api.read_business_message('biz1', 123, 456)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/readBusinessMessage'))
            assert.equals('biz1', req.parameters.business_connection_id)
            assert.equals(123, req.parameters.chat_id)
            assert.equals(456, req.parameters.message_id)
        end)

        it('delete_business_messages JSON-encodes message_ids', function()
            api.delete_business_messages('biz1', { 1, 2, 3 })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/deleteBusinessMessages'))
            assert.equals('biz1', req.parameters.business_connection_id)
            assert.equals(3, #json.decode(req.parameters.message_ids))
        end)

        it('set_business_account_name passes first_name and last_name', function()
            api.set_business_account_name('biz1', 'John', { last_name = 'Doe' })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/setBusinessAccountName'))
            assert.equals('biz1', req.parameters.business_connection_id)
            assert.equals('John', req.parameters.first_name)
            assert.equals('Doe', req.parameters.last_name)
        end)

        it('set_business_account_username passes username', function()
            api.set_business_account_username('biz1', { username = 'newuser' })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/setBusinessAccountUsername'))
            assert.equals('biz1', req.parameters.business_connection_id)
            assert.equals('newuser', req.parameters.username)
        end)

        it('set_business_account_bio passes bio', function()
            api.set_business_account_bio('biz1', { bio = 'a short bio' })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/setBusinessAccountBio'))
            assert.equals('biz1', req.parameters.business_connection_id)
            assert.equals('a short bio', req.parameters.bio)
        end)

        it('set_business_account_profile_photo JSON-encodes photo', function()
            api.set_business_account_profile_photo('biz1', { type = 'static', photo = 'f1' }, { is_public = true })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/setBusinessAccountProfilePhoto'))
            assert.equals('biz1', req.parameters.business_connection_id)
            assert.equals('static', json.decode(req.parameters.photo).type)
            assert.is_true(req.parameters.is_public)
        end)

        it('remove_business_account_profile_photo passes is_public', function()
            api.remove_business_account_profile_photo('biz1', { is_public = true })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/removeBusinessAccountProfilePhoto'))
            assert.equals('biz1', req.parameters.business_connection_id)
            assert.is_true(req.parameters.is_public)
        end)

        it('set_business_account_gift_settings JSON-encodes accepted_gift_types', function()
            api.set_business_account_gift_settings('biz1', true, { unlimited_gifts = true })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/setBusinessAccountGiftSettings'))
            assert.equals('biz1', req.parameters.business_connection_id)
            assert.is_true(req.parameters.show_gift_button)
            assert.is_true(json.decode(req.parameters.accepted_gift_types).unlimited_gifts)
        end)

        it('get_business_account_star_balance passes business_connection_id', function()
            api.get_business_account_star_balance('biz1')
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/getBusinessAccountStarBalance'))
            assert.equals('biz1', req.parameters.business_connection_id)
        end)

        it('transfer_business_account_stars passes star_count', function()
            api.transfer_business_account_stars('biz1', 500)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/transferBusinessAccountStars'))
            assert.equals('biz1', req.parameters.business_connection_id)
            assert.equals(500, req.parameters.star_count)
        end)

        it('get_business_account_gifts passes id and optional filters', function()
            api.get_business_account_gifts('biz1', {
                exclude_unsaved = true,
                exclude_unique = true,
                sort_by_price = true,
                offset = 'next',
                limit = 50
            })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/getBusinessAccountGifts'))
            assert.equals('biz1', req.parameters.business_connection_id)
            assert.is_true(req.parameters.exclude_unsaved)
            assert.is_true(req.parameters.exclude_unique)
            assert.is_true(req.parameters.sort_by_price)
            assert.equals('next', req.parameters.offset)
            assert.equals(50, req.parameters.limit)
        end)

        it('get_business_account_gifts works without opts', function()
            api.get_business_account_gifts('biz1')
            assert.equals('biz1', api._last_request().parameters.business_connection_id)
        end)
    end)

    describe('gift methods', function()
        it('transfer_gift passes ids and star_count', function()
            api.transfer_gift('biz1', 'gift1', 999, { star_count = 25 })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/transferGift'))
            assert.equals('biz1', req.parameters.business_connection_id)
            assert.equals('gift1', req.parameters.owned_gift_id)
            assert.equals(999, req.parameters.new_owner_chat_id)
            assert.equals(25, req.parameters.star_count)
        end)

        it('upgrade_gift passes id and options', function()
            api.upgrade_gift('biz1', 'gift1', { keep_original_details = true, star_count = 10 })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/upgradeGift'))
            assert.equals('biz1', req.parameters.business_connection_id)
            assert.equals('gift1', req.parameters.owned_gift_id)
            assert.is_true(req.parameters.keep_original_details)
            assert.equals(10, req.parameters.star_count)
        end)

        it('convert_gift_to_stars passes ids', function()
            api.convert_gift_to_stars('biz1', 'gift1')
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/convertGiftToStars'))
            assert.equals('biz1', req.parameters.business_connection_id)
            assert.equals('gift1', req.parameters.owned_gift_id)
        end)

        it('gift_premium_subscription JSON-encodes text_entities', function()
            api.gift_premium_subscription(42, 3, 1000, {
                text = 'enjoy',
                text_entities = {{ type = 'bold', offset = 0, length = 5 }}
            })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/giftPremiumSubscription'))
            assert.equals(42, req.parameters.user_id)
            assert.equals(3, req.parameters.month_count)
            assert.equals(1000, req.parameters.star_count)
            assert.equals('enjoy', req.parameters.text)
            assert.equals('bold', json.decode(req.parameters.text_entities)[1].type)
        end)
    end)

    describe('payment methods', function()
        it('get_my_star_balance hits the endpoint with no params', function()
            api.get_my_star_balance()
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/getMyStarBalance'))
        end)
    end)

    describe('checklist methods', function()
        it('edit_message_checklist JSON-encodes checklist and reply_markup', function()
            api.edit_message_checklist('biz1', 123, 456, { title = 'todo' }, {
                reply_markup = api.inline_keyboard():row(api.row():callback_data_button('A', 'a'))
            })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/editMessageChecklist'))
            assert.equals('biz1', req.parameters.business_connection_id)
            assert.equals(123, req.parameters.chat_id)
            assert.equals(456, req.parameters.message_id)
            assert.equals('todo', json.decode(req.parameters.checklist).title)
            assert.is_table(json.decode(req.parameters.reply_markup).inline_keyboard)
        end)
    end)

    describe('chat subscription invite links', function()
        it('create_chat_subscription_invite_link passes period and price', function()
            api.create_chat_subscription_invite_link(123, 2592000, 100, { name = 'sub' })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/createChatSubscriptionInviteLink'))
            assert.equals(123, req.parameters.chat_id)
            assert.equals(2592000, req.parameters.subscription_period)
            assert.equals(100, req.parameters.subscription_price)
            assert.equals('sub', req.parameters.name)
        end)

        it('edit_chat_subscription_invite_link passes invite_link and name', function()
            api.edit_chat_subscription_invite_link(123, 'https://t.me/+abc', { name = 'renamed' })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/editChatSubscriptionInviteLink'))
            assert.equals(123, req.parameters.chat_id)
            assert.equals('https://t.me/+abc', req.parameters.invite_link)
            assert.equals('renamed', req.parameters.name)
        end)
    end)

    describe('story methods', function()
        it('post_story JSON-encodes content, caption_entities and areas', function()
            api.post_story('biz1', { type = 'photo', photo = 'f1' }, 86400, {
                caption = 'hi',
                caption_entities = {{ type = 'bold', offset = 0, length = 2 }},
                areas = {{ position = { x = 1 } }},
                post_to_chat_page = true
            })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/postStory'))
            assert.equals('biz1', req.parameters.business_connection_id)
            assert.equals('photo', json.decode(req.parameters.content).type)
            assert.equals(86400, req.parameters.active_period)
            assert.equals('bold', json.decode(req.parameters.caption_entities)[1].type)
            assert.equals(1, json.decode(req.parameters.areas)[1].position.x)
            assert.is_true(req.parameters.post_to_chat_page)
        end)

        it('edit_story JSON-encodes content and areas', function()
            api.edit_story('biz1', 7, { type = 'video', video = 'v1' }, {
                caption = 'updated',
                areas = {{ position = { x = 2 } }}
            })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/editStory'))
            assert.equals('biz1', req.parameters.business_connection_id)
            assert.equals(7, req.parameters.story_id)
            assert.equals('video', json.decode(req.parameters.content).type)
            assert.equals('updated', req.parameters.caption)
            assert.equals(2, json.decode(req.parameters.areas)[1].position.x)
        end)

        it('delete_story passes business_connection_id and story_id', function()
            api.delete_story('biz1', 7)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/deleteStory'))
            assert.equals('biz1', req.parameters.business_connection_id)
            assert.equals(7, req.parameters.story_id)
        end)
    end)

    describe('verification and emoji status methods', function()
        it('verify_user passes user_id and custom_description', function()
            api.verify_user(42, { custom_description = 'verified' })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/verifyUser'))
            assert.equals(42, req.parameters.user_id)
            assert.equals('verified', req.parameters.custom_description)
        end)

        it('verify_chat passes chat_id and custom_description', function()
            api.verify_chat(123, { custom_description = 'verified' })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/verifyChat'))
            assert.equals(123, req.parameters.chat_id)
            assert.equals('verified', req.parameters.custom_description)
        end)

        it('remove_user_verification passes user_id', function()
            api.remove_user_verification(42)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/removeUserVerification'))
            assert.equals(42, req.parameters.user_id)
        end)

        it('remove_chat_verification passes chat_id', function()
            api.remove_chat_verification(123)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/removeChatVerification'))
            assert.equals(123, req.parameters.chat_id)
        end)

        it('set_user_emoji_status passes user_id and emoji opts', function()
            api.set_user_emoji_status(42, {
                emoji_status_custom_emoji_id = 'emoji1',
                emoji_status_expiration_date = 1700000000
            })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/setUserEmojiStatus'))
            assert.equals(42, req.parameters.user_id)
            assert.equals('emoji1', req.parameters.emoji_status_custom_emoji_id)
            assert.equals(1700000000, req.parameters.emoji_status_expiration_date)
        end)
    end)

    describe('prepared inline messages', function()
        it('save_prepared_inline_message JSON-encodes result and passes flags', function()
            api.save_prepared_inline_message(42, { type = 'article', id = '1', title = 'T' }, {
                allow_user_chats = true,
                allow_group_chats = true
            })
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/savePreparedInlineMessage'))
            assert.equals(42, req.parameters.user_id)
            assert.equals('article', json.decode(req.parameters.result).type)
            assert.is_true(req.parameters.allow_user_chats)
            assert.is_true(req.parameters.allow_group_chats)
        end)

        it('save_prepared_inline_message passes a string result through', function()
            api.save_prepared_inline_message(42, '{"type":"article"}')
            assert.equals('{"type":"article"}', api._last_request().parameters.result)
        end)
    end)
end)
