-- tests for the bot api 10.x send/forward/copy parameter extensions:
-- direct_messages_topic_id (scalar) and suggested_post_parameters (json object)
local api = require('spec.test_helper')
local json = require('dkjson')

describe('send/forward/copy parameter extensions', function()
    before_each(function()
        api._clear_requests()
    end)

    -- opts carrying both new parameters
    local both = { direct_messages_topic_id = 7, suggested_post_parameters = { price = 5 } }
    -- opts carrying only direct_messages_topic_id (for the direct-messages-only methods)
    local dm_only = { direct_messages_topic_id = 7 }

    -- assert the request carries direct_messages_topic_id as a raw scalar
    local function assert_topic(req)
        assert.equals(7, req.parameters.direct_messages_topic_id)
    end

    -- assert the request carries a json-encoded suggested_post_parameters object
    local function assert_suggested(req)
        assert.equals(5, json.decode(req.parameters.suggested_post_parameters).price)
    end

    describe('messages.lua', function()
        it('send_message carries both parameters', function()
            api.send_message(123, 'hi', both)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendMessage'))
            assert_topic(req)
            assert_suggested(req)
        end)

        it('forward_message carries both parameters', function()
            api.forward_message(123, 456, 789, both)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/forwardMessage'))
            assert_topic(req)
            assert_suggested(req)
        end)

        it('forward_messages carries direct_messages_topic_id only', function()
            api.forward_messages(123, 456, { 1, 2 }, dm_only)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/forwardMessages'))
            assert_topic(req)
            assert.is_nil(req.parameters.suggested_post_parameters)
        end)

        it('copy_message carries both parameters', function()
            api.copy_message(123, 456, 789, both)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/copyMessage'))
            assert_topic(req)
            assert_suggested(req)
        end)

        it('copy_messages carries direct_messages_topic_id only', function()
            api.copy_messages(123, 456, { 1, 2 }, dm_only)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/copyMessages'))
            assert_topic(req)
            assert.is_nil(req.parameters.suggested_post_parameters)
        end)

        it('send_photo carries both parameters', function()
            api.send_photo(123, 'photo_id', both)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendPhoto'))
            assert_topic(req)
            assert_suggested(req)
        end)

        it('send_audio carries both parameters', function()
            api.send_audio(123, 'audio_id', both)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendAudio'))
            assert_topic(req)
            assert_suggested(req)
        end)

        it('send_document carries both parameters', function()
            api.send_document(123, 'doc_id', both)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendDocument'))
            assert_topic(req)
            assert_suggested(req)
        end)

        it('send_video carries both parameters', function()
            api.send_video(123, 'video_id', both)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendVideo'))
            assert_topic(req)
            assert_suggested(req)
        end)

        it('send_animation carries both parameters', function()
            api.send_animation(123, 'anim_id', both)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendAnimation'))
            assert_topic(req)
            assert_suggested(req)
        end)

        it('send_voice carries both parameters', function()
            api.send_voice(123, 'voice_id', both)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendVoice'))
            assert_topic(req)
            assert_suggested(req)
        end)

        it('send_video_note carries both parameters', function()
            api.send_video_note(123, 'note_id', both)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendVideoNote'))
            assert_topic(req)
            assert_suggested(req)
        end)

        it('send_paid_media carries both parameters', function()
            api.send_paid_media(123, 5, { { type = 'photo', media = 'm' } }, both)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendPaidMedia'))
            assert_topic(req)
            assert_suggested(req)
        end)

        it('send_media_group carries direct_messages_topic_id only', function()
            api.send_media_group(123, { { type = 'photo', media = 'm' } }, dm_only)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendMediaGroup'))
            assert_topic(req)
            assert.is_nil(req.parameters.suggested_post_parameters)
        end)

        it('send_location carries both parameters', function()
            api.send_location(123, 51.5, -0.1, both)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendLocation'))
            assert_topic(req)
            assert_suggested(req)
        end)

        it('send_venue carries both parameters', function()
            api.send_venue(123, 51.5, -0.1, 'Title', 'Address', both)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendVenue'))
            assert_topic(req)
            assert_suggested(req)
        end)

        it('send_contact carries both parameters', function()
            api.send_contact(123, '+440000000000', 'First', both)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendContact'))
            assert_topic(req)
            assert_suggested(req)
        end)

        it('send_dice carries both parameters', function()
            api.send_dice(123, both)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendDice'))
            assert_topic(req)
            assert_suggested(req)
        end)
    end)

    describe('stickers.lua', function()
        it('send_sticker carries both parameters', function()
            api.send_sticker(123, 'sticker_id', both)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendSticker'))
            assert_topic(req)
            assert_suggested(req)
        end)
    end)

    describe('payments.lua', function()
        it('send_invoice carries both parameters', function()
            api.send_invoice(123, 'Title', 'Desc', 'payload', 'XTR',
                { { label = 'item', amount = 100 } }, both)
            local req = api._last_request()
            assert.truthy(req.endpoint:find('/sendInvoice'))
            assert_topic(req)
            assert_suggested(req)
        end)
    end)
end)
