name: Lua CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Lua
      uses: hishamhm/gh-actions-lua@v7
      with:
        luaVersion: "5.1"

    - name: Setup LuaRocks
      uses: hishamhm/gh-actions-luarocks@v4

    - name: Install Linting Tools
      run: luarocks install luacheck

    - name: Run Lint Check
      run: luacheck .
